### ISSUE TITLE
[QUESTION] This package is compatible with which Unity version?

### ISSUE THREAD

**Issue by niscolas** [Domeee/com.cloudedmountain.ide.neovim#1]
I wasn't able to make it work on 2021.2.17f1 without adding an `CodeEditor.Register(new NeovimCodeEditor())` at the beginning of the NeovimCodeEditor static constructor.
I believe that the API has changed since the version stated on the `package.json`.
Besides that, the Sync Solution method is giving errors too, I believe that's for the same reason (API change).

**Comment by Domeee** [comment]
Hi @niscolas 

This project currently supports unity 2019.x.

Just last week I migrated a project from unity 2019.x to 2020.x and realized that the unity api used in this project was removed.

Unity 202x support is currently work in progress.

**Comment by niscolas** [comment]
I recently discovered this repo: https://github.com/HelpOrMe/com.unity.ide.neovim
It's a fork of the Jetbrains Rider Extension for Unity, but with support for Neovim. 

I opened a pull request with the additions I mentioned on this Issue description, but the owner didn't answer (yet), so [my fork](https://github.com/niscolas/com.unity.ide.neovim) is working pretty nicely on newer Unity versions since it has the full project file recreation builtin (and the Rider integration is far superior compared to the VS one)
