### ISSUE TITLE
Issue: Clicking Browse

### ISSUE THREAD

**Issue by Yumshot** [Domeee/com.cloudedmountain.ide.neovim#3]
Downloaded the JSON, installed it, and on accident ended up clicking the browse button, removing the neovim option from the listed editors.
What path does it normally try to grab?

**Comment by Domeee** [comment]
Hi @Yumshot 

The path is set here: https://github.com/Domeee/com.cloudedmountain.ide.neovim/blob/master/Editor/VSCodeDiscovery.cs#L48

HTH

**Comment by Yumshot** [comment]
Appreciate it, Seems for Windows it runs the nvim-qt.exe and defines the editor as (internal) which had been throwing me off.
Some things to note, Im using it with 2021.3.19f1. It seems like I got LSP without using the command and just having omnisharp LSP already installed. (noted because the json say 2019 versioning) 
I believe the package was adding the arguments ```External Script Editor: pwsh External Script Editor Args: -WindowStyle Normal -Command nvim $(File)``` which did not work for me, but swapping to the default $(File) did. Appreciate the package, Ill close this as my issue is solved.
