### ISSUE TITLE
File was opened but no data is displayed!

### ISSUE THREAD

**Issue by NTTKDeveloper** [Domeee/com.cloudedmountain.ide.neovim#4]
The file was opened with its folder included, but there was nothing in it. Can't save when saving it says file not found.
What happened!

Neovim 0.10

![image](https://github.com/Domeee/com.cloudedmountain.ide.neovim/assets/85882940/07858543-40cc-4312-9db8-240303046263)

**Comment by vishless** [comment]
I'm facing the same issue. The file opens but it's empty. @NTTKDeveloper were you able to find a solution?

Edit: This was because the project name had a space in it.

**Comment by Domeee** [comment]
I updated the troubleshooting section of the readme section accordingly. PR welcome
