### ISSUE TITLE
[Feature Request] Integrate with OpenUPM?

### ISSUE THREAD

**Issue by ugnmura** [Domeee/com.cloudedmountain.ide.neovim#5]
Seems like this package has no release, which makes the package unusable for OpenUPM. It would be nice to have a release since it would make it possible to install the package via the command line.

**Comment by Domeee** [comment]
I am not familiar with OpenUPM. Is this what you require: https://github.com/Domeee/com.cloudedmountain.ide.neovim/releases/tag/v0.0.1

**Comment by ugnmura** [comment]
Yes this is exactly what I needed thanks!
Now it is on [OpenUPM](https://openupm.com/packages/com.cloudedmountain.ide.neovim/).
